on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    types: [ "opened", "synchronize", "review_requested", "ready_for_review" ]
  workflow_dispatch:
name: Linux
permissions:
  contents: read
env:
  GITHUB_ACTIONS: true
jobs:
  build:
    name: "Build on Linux"
    strategy:
      matrix:
        variant:
          - arch: x64
            runner: ubuntu-latest
            triplet: x64-linux
          - arch: arm64
            runner: ubuntu-24.04-arm
            triplet: arm64-linux
    runs-on: ${{ matrix.variant.runner }}
    container:
          image: fedora:44
    steps:
      - name: "Setup Environment"
        run: |
          mkdir build
          dnf install -y curl cmake dbus-x11 gcc gcc-c++ gettext-devel git glib2-devel gnome-keyring gtest-devel json-devel libarchive-devel libsecret libsecret-devel ninja-build openssl-devel pkgconfig
          git clone --branch 1.6.0 https://github.com/progsource/maddy /tmp/maddy
          cmake -S /tmp/maddy -B /tmp/maddy/build -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=/usr
          cmake --build /tmp/maddy/build
          cmake --install /tmp/maddy/build
      - name: "Checkout"
        uses: actions/checkout@v6
        with:
          submodules: recursive
      - name: "Unlock Keyring"
        run: |
          export $(dbus-launch)
          echo "" | gnome-keyring-daemon --unlock --components=secrets --no-lock-memory
          echo "DBUS_SESSION_BUS_ADDRESS=$DBUS_SESSION_BUS_ADDRESS" >> $GITHUB_ENV
      - name: "Build"
        working-directory: ${{github.workspace}}/build
        run: |
          cmake .. -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=${{github.workspace}}/install -DCMAKE_CXX_STANDARD=20
          cmake --build . --parallel
      - name: "Install"
        working-directory: ${{github.workspace}}/build
        run: cmake --install .
      - name: "Test"
        working-directory: ${{github.workspace}}/build
        run: ctest --output-on-failure
      - name: Upload
        uses: actions/upload-artifact@v7
        with:
          path: ${{github.workspace}}/install
          name: Linux-${{ matrix.variant.arch }}-Release
