on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    types: [ "opened", "synchronize", "review_requested", "ready_for_review" ]
  workflow_dispatch:
name: macOS
permissions:
  contents: read
env:
  GITHUB_ACTIONS: true
jobs:
  build:
    name: "Build on macOS"
    strategy:
      matrix:
        variant:
          - arch: x64
            runner: macos-26-intel
            triplet: x64-osx
            prefix: /usr/local
          - arch: arm64
            runner: macos-26
            triplet: arm64-osx
            prefix: /opt/homebrew
    runs-on: ${{ matrix.variant.runner }}
    steps:
      - name: "Checkout"  
        uses: actions/checkout@v6
        with:
          submodules: recursive
      - name: "Setup Environment"
        run: |
          mkdir build
          brew update
          brew install curl gettext glib googletest libarchive nlohmann-json openssl
          git clone --branch 1.6.0 https://github.com/progsource/maddy /tmp/maddy
          cmake -S /tmp/maddy -B /tmp/maddy/build -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=${{ matrix.variant.prefix }}
          cmake --build /tmp/maddy/build
          sudo cmake --install /tmp/maddy/build
      - name: "Setup Keychain"
        run: |
          security create-keychain -p libdesktop-ci libdesktop-ci.keychain
          security set-keychain-settings -lut 21600 libdesktop-ci.keychain
          security unlock-keychain -p libdesktop-ci libdesktop-ci.keychain
          security list-keychains -d user -s libdesktop-ci.keychain
          security default-keychain -d user -s libdesktop-ci.keychain
      - name: "Build"
        working-directory: ${{github.workspace}}/build
        run: |
          cmake .. -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=${{github.workspace}}/install -DCMAKE_CXX_STANDARD=20
          cmake --build . --parallel
      - name: "Install"
        working-directory: ${{github.workspace}}/build
        run: cmake --install .
      - name: "Test"
        working-directory: ${{github.workspace}}/build
        run: ctest --output-on-failure
      - name: Upload
        uses: actions/upload-artifact@v7
        with:
          path: ${{github.workspace}}/install
          name: macOS-${{ matrix.variant.arch }}-Release
