on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    types: [ "review_requested", "ready_for_review" ]
  workflow_dispatch:
name: Windows
permissions:
  contents: read
env:
  GITHUB_ACTIONS: true
  VCPKG_ROOT: ${{ github.workspace }}/vcpkg
jobs:
  build:
    name: "Build on Windows"
    strategy:
      matrix:
        variant:
          - arch: x64
            runner: windows-latest
            triplet: x64-windows
          - arch: arm64
            runner: windows-11-arm
            triplet: arm64-windows
    runs-on: ${{ matrix.variant.runner }}
    steps:
      - name: "Checkout"  
        uses: actions/checkout@v6
        with:
          submodules: recursive
      - name: "Setup Environment"
        run: mkdir build
      - name: "Vcpkg"
        uses: johnwason/vcpkg-action@v7
        id: vcpkg
        with:
          pkgs: curl gettext-libintl gtest maddy nlohmann_json openssl
          triplet: ${{ matrix.variant.triplet }}
          revision: 432412eecac55981cf608cc12e5b4bd91768ec57
          token: ${{ github.token }}
          cache-key: ${{ matrix.variant.triplet }}
      - name: "Build"
        working-directory: ${{github.workspace}}/build
        run: |
          cmake -G "Visual Studio 18 2026" .. -DCMAKE_INSTALL_PREFIX=${{github.workspace}}/install -DCMAKE_CXX_STANDARD=20
          cmake --build . --config Release --parallel
      - name: "Install"
        working-directory: ${{github.workspace}}/build
        run: cmake --install . --config Release
      - name: "Test"
        working-directory: ${{github.workspace}}/build
        run: ctest --config Release --output-on-failure
      - name: Upload
        uses: actions/upload-artifact@v7
        with:
          path: ${{github.workspace}}/install
          name: Windows-${{ matrix.variant.arch }}-Release
